id: I611C6D68
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T03:41:49+00:00'
last_modified: '2022-06-16T04:47:13.566787+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W942
  title: དགེ་ལྡན་ལེགས་བཤད་པདྨ་དཀར་པོའི་ཆུན་པོའི་ཆུན་པོའི་འགྲེལ་པ་ཉི་མའི་འོད་ཟེར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    43D6:
      image_group_id: I1KG14819
      title: Volume 1 of dge ldan legs bshad pad+ma dkar po'i chun po'i chun po'i
        'grel pa nyi ma'i 'od zer/
      total_pages: 196
      order: 1
      base_file: 43D6.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
